train_vars = ('rrp',
              'stock',
              'brand_hash_0',
              'brand_hash_1',
              'brand_hash_2',
              'brand_hash_3',
              'brand_hash_4',
              'brand_hash_5',
              'brand_hash_6',
              'brand_hash_7',
              'brand_hash_8',
              'brand_hash_9',
              'brand_hash_10',
              'brand_hash_11',
              'color_hash_0',
              'color_hash_1',
              'color_hash_2',
              'color_hash_3',
              'color_hash_4',
              'color_hash_5',
              'color_hash_6',
              'color_hash_7',
              'mainCategory_onehot_1',
              'mainCategory_onehot_9',
              'mainCategory_onehot_15',
              )

